# creation rules are evaluated sequentially, the first match wins
creation_rules:
        - path_regex: overlays/test/sops_.*\.yaml$
          pgp: '34AFE2A7C8E00ED66916D95DA9FBD7DE773B2A34, 87FC5D0ACF3AA48FCC029086262A80E41BCEEBF7'

