---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: graph-sync
  annotations:
    thoth-station.ninja/template-version: 0.6.0-dev
  labels:
    app: thoth
    component: graph-sync
spec:
  templates:
    - name: graph-sync
      inputs:
        parameters:
          - name: "THOTH_DOCUMENT_ID"
          - name: "THOTH_FORCE_SYNC"
          - name: "IMAGE_STREAM_REGISTRY"
          - name: "IMAGE_STREAM_NAMESPACE"
          - name: "IMAGE_STREAM_TAG"
        artifacts:
          - name: "outputdocument"
            path: "/mnt/component/document/{{inputs.parameters.THOTH_DOCUMENT_ID}}"
      retryStrategy:
        limit: 3
      container:
        name: "graph-sync"
        image: "{{inputs.parameters.IMAGE_STREAM_REGISTRY}}/\
        {{inputs.parameters.IMAGE_STREAM_NAMESPACE}}/\
        graph-sync-job:{{inputs.parameters.IMAGE_STREAM_TAG}}"
        env:
          - name: "THOTH_DOCUMENT_ID"
            value: "{{inputs.parameters.THOTH_DOCUMENT_ID}}"
          - name: "THOTH_SYNC_LOCAL_FILE"
            value: "1"
          - name: "THOTH_SYNC_DOCUMENT_ID"
            value: "/mnt/component/document/{{inputs.parameters.THOTH_DOCUMENT_ID}}"
          - name: "THOTH_FORCE_SYNC"
            value: "{{inputs.parameters.THOTH_FORCE_SYNC}}"
          - name: "THOTH_LOG_GRAPH_SYNC_JOB"
            value: "DEBUG"
          - name: "THOTH_DEPLOYMENT_NAME"
            valueFrom:
              configMapKeyRef:
                key: storage-bucket-name
                name: thoth
          - name: AMUN_API_URL
            valueFrom:
              configMapKeyRef:
                key: amun-api-url
                name: thoth
          - name: THOTH_S3_ENDPOINT_URL
            valueFrom:
              configMapKeyRef:
                key: ceph-host
                name: thoth
          - name: THOTH_CEPH_BUCKET
            valueFrom:
              configMapKeyRef:
                key: ceph-bucket-name
                name: thoth
          - name: THOTH_CEPH_BUCKET_PREFIX
            valueFrom:
              configMapKeyRef:
                key: ceph-bucket-prefix
                name: thoth
          - name: THOTH_CEPH_KEY_ID
            valueFrom:
              secretKeyRef:
                name: thoth
                key: ceph-key-id
          - name: THOTH_CEPH_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: thoth
                key: ceph-secret-key
          - name: THOTH_METRICS_PUSHGATEWAY_URL
            valueFrom:
              configMapKeyRef:
                name: thoth
                key: metrics-pushgateway-url
          - name: "THOTH_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SENTRY_DSN
            valueFrom:
              secretKeyRef:
                name: thoth
                key: sentry-dsn
          - name: KNOWLEDGE_GRAPH_HOST
            valueFrom:
              configMapKeyRef:
                key: postgresql-host
                name: thoth
          - name: KNOWLEDGE_GRAPH_PORT
            value: "5432"
          - name: KNOWLEDGE_GRAPH_SSL_DISABLED
            value: "1"
          - name: KNOWLEDGE_GRAPH_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-user
          - name: KNOWLEDGE_GRAPH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-password
          - name: KNOWLEDGE_GRAPH_DATABASE
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: database-name
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
