---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: thoth
    component: init-job
  name: init-job
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/thoth-station/init-job:v0.6.0-dev
      importPolicy: {}
      referencePolicy:
        type: Source
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: thoth
    component: result-api
  name: result-api
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: quay.io/thoth-station/result-api:v0.6.0-dev
      importPolicy: {}
      referencePolicy:
        type: Source
