---
kind: Job
apiVersion: batch/v1
metadata:
  name: init-job
spec:
  template:
    spec:
      containers:
        - name: init-job
          image: image-registry.openshift-image-registry.svc:5000/thoth-int/init-job:latest
